### ISSUE TITLE
2131207 - Uncaught exception: com.google.gwt.core.client.JavaScriptException: (TypeError) : a is null

### ISSUE THREAD

**Issue by sgratch** [oVirt/ovirt-engine#698]
Version-Release number:  oVirt 4.5.2

Description of problem: Storage -> Domains - selecting a backup domain, -> VM Import - selecting the VM to be imported - clicking on import throws the following exception : ERROR [org.ovirt.engine.ui.frontend.server.gwt.OvirtRemoteLoggingService] (default task-22) [] Uncaught exception: com.google.gwt.core.client.JavaScriptException: (TypeError) : a is null at java.math.Conversion.toDecimalScaledString(Conversion.java:175)

Additional info: ui.logs

```
2022-09-30 11:25:33,566+02 ERROR [org.ovirt.engine.ui.frontend.server.gwt.OvirtRemoteLoggingService] (default task-22) [] Permutation name: 0F30747C728BDB3681A1A49DB43DD469
2022-09-30 11:25:33,566+02 ERROR [org.ovirt.engine.ui.frontend.server.gwt.OvirtRemoteLoggingService] (default task-22) [] Uncaught exception: com.google.gwt.core.client.JavaScriptException: (TypeError) : a is null
	at java.math.Conversion.toDecimalScaledString(Conversion.java:175)
	at org.ovirt.engine.ui.webadmin.section.main.view.popup.storage.RegisterEntityInfoPanel$18.$getRawValue(RegisterEntityInfoPanel.java:314)
	at org.ovirt.engine.ui.webadmin.section.main.view.popup.storage.RegisterEntityInfoPanel$18.getRawValue(RegisterEntityInfoPanel.java:314)
	at org.ovirt.engine.ui.common.widget.table.column.AbstractRenderedTextColumn.$getValue(AbstractRenderedTextColumn.java:24)
	at org.ovirt.engine.ui.common.widget.table.column.AbstractRenderedTextColumn.getValue(AbstractRenderedTextColumn.java:24)
	at org.ovirt.engine.ui.common.widget.table.column.AbstractRenderedTextColumn.getValue(AbstractRenderedTextColumn.java:24)
	at com.google.gwt.user.cellview.client.Column.render(Column.java:164)
	at com.google.gwt.user.cellview.client.AbstractCellTableBuilder.$renderCell(AbstractCellTableBuilder.java:188)
	at com.google.gwt.user.cellview.client.DefaultCellTableBuilder.$buildRowImpl(DefaultCellTableBuilder.java:62)
	at com.google.gwt.user.cellview.client.AbstractCellTableBuilder.$buildRow(AbstractCellTableBuilder.java:85)
	at com.google.gwt.user.cellview.client.AbstractCellTable.$buildRowValues(AbstractCellTable.java:2350)
	at com.google.gwt.user.cellview.client.AbstractCellTable.replaceAllChildren(AbstractCellTable.java:2149)
	at com.google.gwt.user.cellview.client.AbstractHasData$View.replaceAllChildren(AbstractHasData.java:265)
	at com.google.gwt.user.cellview.client.HasDataPresenter.$resolvePendingState(HasDataPresenter.java:1062)
	at com.google.gwt.user.cellview.client.HasDataPresenter$2.execute(HasDataPresenter.java:981)
	at com.google.gwt.core.client.impl.SchedulerImpl.runScheduledTasks(SchedulerImpl.java:167)
	at com.google.gwt.core.client.impl.SchedulerImpl.$flushFinallyCommands(SchedulerImpl.java:272)
	at com.google.gwt.core.client.impl.Impl.exit(Impl.java:383)
	at com.google.gwt.core.client.impl.Impl.entry0(Impl.java:345)
	at Unknown.My/<(https://lcsb-cdc-int-engine-01.uni.lux/ovirt-engine/webadmin/?locale=en_US line 9 > injectedScript)
	at Unknown.anonymous(Unknown)
```

Original bug reported by noua.toukourou@uni.lu:  https://bugzilla.redhat.com/show_bug.cgi?id=2131207

**Comment by ahadas** [comment]
While this issue happens during register VM, which is indeed a flow that was owned by the storage team, the problem is on handling network statistics - seems to be a consequence of the fix for https://bugzilla.redhat.com/1980192. It was reported on d/s: https://bugzilla.redhat.com/2130503
