### ISSUE TITLE
MoM functionality is broken in mom-0.6.3-1.el8ev.noarch -  Failed to initialize MOM threads

### ISSUE THREAD

**Issue by polinaag** [oVirt/ovirt-engine#712]
The ballooning deflation feature doesn't work ( the ballooning stats  remain unchanged  upon allocating memory from host), described in scenario1.
Also, NUMA awareness KSM policy doesn't function, described in scenario2.
in mom log we see:
2022-10-20 10:52:28,566 - mom - ERROR - Failed to initialize MOM threads
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/mom/__init__.py", line 35, in run
    host_monitor, guest_manager)
  File "/usr/lib/python3.6/site-packages/mom/PolicyEngine.py", line 42, in __init__
    self.load_policy()
  File "/usr/lib/python3.6/site-packages/mom/PolicyEngine.py", line 71, in load_policy
    read_policy(fname, name.split('.policy')[0])
  File "/usr/lib/python3.6/site-packages/mom/PolicyEngine.py", line 53, in read_policy
    return self.policy.set_policy(policy_name, policyStr)
  File "/usr/lib/python3.6/site-packages/mom/Policy/Policy.py", line 64, in set_policy
    self.code = get_code(Evaluator(), self._cat_policies())
  File "/usr/lib/python3.6/site-packages/mom/Policy/Parser.py", line 543, in get_code
    tokens = scanner.tokenize(string)
  File "/usr/lib/python3.6/site-packages/mom/Policy/Parser.py", line 72, in tokenize
    GenericScanner.tokenize(self, input)
  File "/usr/lib/python3.6/site-packages/mom/Policy/spark.py", line 78, in tokenize
    add_lines = self.index2func[i](groups[i], line)
TypeError: t_default() takes 2 positional arguments but 3 were given

Tested that rpm mom-0.6.4-0.0.master.20221020090505.gitb847671.el8.noarch.rpm fixes this 
[mom.log.gz](https://github.com/oVirt/ovirt-engine/files/9830555/mom.log.gz)
issue.

scenario1 :Description of the deflation test.
1. Change MOM pressure threshold
   set in /etc/vdsm/mom.d/02-balloon.policy a line -  (defvar pressure_threshold 0.40)
   Enable ballooning on the host: 1) Update cluster ballooning 2) Deactivate the host 3) Activate the host.
2. Configure memory on VM and start VM.
   Memory Size: 2048 MB
   Maximum memory: 4096 MB
   Physical Memory Guaranteed: 1024 MB
3. Allocate host memory.
   Get free memory by GET statistics request and allocate 70% of free memory.
       resourse free memory = 31066171638.0 (returned by GET https://{{host}}/ovirt-engine/api/hosts/a7eed758-67c9-4d8c-8e4a-3be97ad4b880/statistics request)
 <statistic href="/ovirt-engine/api/hosts/a7eed758-67c9-4d8c-8e4a-3be97ad4b880/statistics/5a0fba9d-33d7-3cbf-addd-ba462040c946" id="5a0fba9d-33d7-3cbf-addd-ba462040c946">        
<name>memory.free</name>
        <description>Free memory</description>
        <kind>gauge</kind>
        <type>integer</type>
        <unit>bytes</unit>
        <values>
            <value>
                <datum>31066171638</datum>
            </value>
        </values>
        <host href="/ovirt-engine/api/hosts/a7eed758-67c9-4d8c-8e4a-3be97ad4b880" id="a7eed758-67c9-4d8c-8e4a-3be97ad4b880"/>
    </statistic>
 Allocate host host_mixed_1 memory
   resourse free memory = 31066171638.0
   Allocating 21746320146 B of memory on host Host(10.46.16.37)

4. While allocating memory, wait for the VM's ballooning info to change. For that run on host the following command in a loop with wait.
    vdsm-client VM getStats vmID="2491b423-3b4d-4468-95dc-949f35c1d305"
the output at the beginning looks like that.
     "balloonInfo": {
            "balloon_cur": "2097152",
            "balloon_max": "2097152",
            "balloon_min": "2097152",
            "balloon_target": "2097152",
            "ballooning_enabled": true
then it must changed like 
 "balloonInfo": {
            "balloon_cur": "1708036",
            "balloon_max": "2097152",
            "balloon_min": "1048576",
            "balloon_target": "1708035",
            "ballooning_enabled": true

scenario2: NUMA awareness KSM policy 

PUT request content is --  url:/ovirt-engine/api/clusters/e4741787-37bc-4566-8559-c673c7023c54 body:
<cluster>
<ksm>
        <enabled>true</enabled>
        <merge_across_nodes>false</merge_across_nodes>
    </ksm>
    <migration>
        <policy/>
    </migration>
</cluster>

then deactivates /activates the host and expects to see 
cat /sys/kernel/mm/ksm/merge_across_nodes equals to 0. But this file always contains 1. even if I manually try KSM enable/disable it doesn't affect .

**Comment by mz-pdm** [comment]
https://github.com/oVirt/mom/pull/17 fixes the traceback above and the followup problems.
