### ISSUE TITLE
setCpuTuneQuota: libvirt.libvirtError Invalid value "-1" for "cpu.max": Invalid argument

### ISSUE THREAD

**Issue by slavonnet** [oVirt/ovirt-engine#778]
Locale is Russian. Error translate is "libvirt.libvirtError Invalid value "-1" for "cpu.max": Invalid argument"
```
2022-12-09 18:35:13,238+0300 INFO  (jsonrpc/4) [api.virt] START setCpuTuneQuota(quota=-1) from=::1,55764, vmId=7ddfee1e-131d-46c7-a6e2-2da4b7031990 (api:31)
2022-12-09 18:35:13,240+0300 ERROR (jsonrpc/4) [virt.vm] (vmId='7ddfee1e-131d-46c7-a6e2-2da4b7031990') Operation failed (vm:5605)
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/vdsm/virt/vm.py", line 5570, in setCpuTuneQuota
    self._dom.setSchedulerParameters({'vcpu_quota': int(quota)})
  File "/usr/lib/python3.9/site-packages/vdsm/virt/virdomain.py", line 104, in f
    ret = attr(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/vdsm/common/libvirtconnection.py", line 114, in wrapper
    ret = f(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/vdsm/common/function.py", line 78, in wrapper
    return func(inst, *args, **kwargs)
  File "/usr/lib64/python3.9/site-packages/libvirt.py", line 2863, in setSchedulerParameters
    raise libvirtError('virDomainSetSchedulerParameters() failed')
libvirt.libvirtError: Недопустимое значение «-1» для «cpu.max»: Недопустимый аргумент
2022-12-09 18:35:13,240+0300 INFO  (jsonrpc/4) [api.virt] FINISH setCpuTuneQuota return={'status': {'code': 62, 'message': 'Недопустимое значение «-1» для «cpu.max»: Недопустимый аргумент'}} from=::1,55764, vmId=7ddfee1e-131d-46c7-a6e2-2da4b7031990 (api:37)
```

oVirt 4.5.4
Host:
OS Version: RHEL - 9.0 - 18.el9
OS Description: CentOS Stream 9
Kernel Version: 5.14.0 - 205.el9.x86_64
KVM Version:  7.1.0 - 5.el9
LIBVIRT Version: libvirt-8.9.0-2.el9
VDSM Version: vdsm-4.50.3.4-1.el9
SPICE Version:
GlusterFS Version: [N/A]
CEPH Version: librbd1-16.2.10-1.el9s
Open vSwitch Version: openvswitch-2.15-4.el9
Nmstate Version: nmstate-2.2.2-0.alpha.20221201.el9

**Comment by antonios-f** [comment]
This is a libvirt issue. It was fixed in https://gitlab.com/libvirt/libvirt/-/commit/9233f0fa8c8e031197c647f7bc980dee45283641.

**Comment by sandrobonazzola** [comment]
@slavonnet I would suggest to report it to RHEL 9 product, CentOS Stream version on https://bugzilla.redhat.com/
according to @antonios-f comment.
