### ISSUE TITLE
org.pos tgresql.util.PSQLException:An I/O error occurred while sending to the backend

### ISSUE THREAD

**Issue by scylla999** [oVirt/ovirt-engine#858]
Ovirt engine version: 4.5.4
4.18.0-448.el8.x86_64 #1 SMP Wed Jan 18 15:02:46 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

workaround:  systemctl restart ovirt-engine-dwhd

We regurlary get connection errors between ovirt_engine and Postgresql DB:

Exception in component tJDBCInput_3
org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:339)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
        at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
        at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:226)
        at ovirt_engine_dwh.hourlytimekeepingjob_4_5.HourlyTimeKeepingJob.tJDBCInput_3Process(HourlyTimeKeepingJob.java:1528
)
        at ovirt_engine_dwh.hourlytimekeepingjob_4_5.HourlyTimeKeepingJob.tJDBCConnection_3Process(HourlyTimeKeepingJob.java
:1258)
        at ovirt_engine_dwh.hourlytimekeepingjob_4_5.HourlyTimeKeepingJob.tPostjob_1Process(HourlyTimeKeepingJob.java:1133)
        at ovirt_engine_dwh.hourlytimekeepingjob_4_5.HourlyTimeKeepingJob.runJobInTOS(HourlyTimeKeepingJob.java:9507)
        at ovirt_engine_dwh.hourlytimekeepingjob_4_5.HourlyTimeKeepingJob.runJob(HourlyTimeKeepingJob.java:9158)
        at ovirt_engine_dwh.parallelrun_4_5.ParallelRun.tInfiniteLoop_2Process(ParallelRun.java:3123)
        at ovirt_engine_dwh.parallelrun_4_5.ParallelRun.tJava_3Process(ParallelRun.java:2884)
        at ovirt_engine_dwh.parallelrun_4_5.ParallelRun$3.run(ParallelRun.java:5666)
Caused by: java.io.IOException: Stream closed
        at java.base/sun.nio.cs.StreamEncoder.ensureOpen(StreamEncoder.java:45)
        at java.base/sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:152)
        at java.base/java.io.OutputStreamWriter.flush(OutputStreamWriter.java:251)
        at org.postgresql.core.PGStream.flush(PGStream.java:590)
        at org.postgresql.core.v3.QueryExecutorImpl.sendSync(QueryExecutorImpl.java:1458)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
        ... 14 more
2023-05-31 00:00:00|eMcc7R|LF7Voe|9G7wTL|OVIRT_ENGINE_DWH|HourlyTimeKeepingJob|Default|6|Java Exception|tJDBCInput_3|org.pos
tgresql.util.PSQLException:An I/O error occurred while sending to the backend.|1
2023-05-31 00:00:00|RCbfli|LF7Voe|9G7wTL|OVIRT_ENGINE_DWH|HourlyTimeKeepingJob|Default|5|tWarn|tWarn_1|2023-05-31 00:00:00| 
ETL service aggregation to hourly tables has encountered an error. lastHourAgg value =Tue May 30 23:00:00 EDT 2023 and runTi
me = Wed May 31 00:00:00 EDT 2023 .Please consult the service log for more details.|42

Anyone have an idea on how to resolve this?

**Comment by scylla999** [comment]
Extra info:

- Time zone: America/New_York (EDT, -0400)
- System clock synchronized: yes
- NTP service: n/a
- RTC in local TZ: no

sudo --user=postgres --login psql --dbname=ovirt_engine_history --command='show timezone;'     TimeZone     
------------------
 America/New_York
(1 row)

**Comment by dupondje** [comment]
Seems like an issue with postgresql connection.
Can you try if you are able to reproduce it somehow on a newer OS (CentOS 9 / CentOS 10) with the latest ovirt-engine/ovirt-dwh?
